export const categories={outros:'A identificar / outra',expediente:'Material de expediente',energia:'Energia',aluguel:'Aluguel',pessoal:'Salários e encargos',beneficios:'Benefícios',equipamento:'Equipamento durável',veiculo:'Veículo do titular',irpf:'IRPF do titular',repasse:'Repasses legais',misto:'Uso misto'};
export const labels={dedutivel:'Dedutível',nao:'Não dedutível',analise:'Análise específica',pendente:'A classificar'};
export const eligible=e=>e.treatment==='dedutivel'&&e.reviewed&&e.docsConfirmed&&e.paymentConfirmed&&e.docIds.length>0;
export const pending=e=>!e.reviewed||!e.docsConfirmed||!e.paymentConfirmed||!e.docIds.length||e.treatment==='pendente'||e.treatment==='analise';
export const totals=list=>({total:list.reduce((n,e)=>n+e.cents,0),deduct:list.filter(eligible).reduce((n,e)=>n+e.cents,0),non:list.filter(e=>e.treatment==='nao'&&e.reviewed).reduce((n,e)=>n+e.cents,0),pending:list.filter(pending).length});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n/100);
const decimal=n=>(n/100).toFixed(2).replace('.',',');
const date=s=>s.split('-').reverse().join('/');
function validDate(s){if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return false;const d=new Date(s+'T12:00:00Z');return !Number.isNaN(+d)&&d.toISOString().slice(0,10)===s;}
export function monthRange(month){if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month))throw new Error('Selecione um mês válido.');const [year,m]=month.split('-').map(Number);const last=new Date(Date.UTC(year,m,0)).getUTCDate();return {from:month+'-01',to:month+'-'+last};}
export function selectExpenses(entries,{from,to,category=''}){
 if(!validDate(from)||!validDate(to)||from>to)throw new Error('Informe um intervalo válido: a data inicial deve ser igual ou anterior à final.');
 if(category&&!Object.hasOwn(categories,category))throw new Error('Selecione uma natureza válida.');
 return entries.filter(e=>!e.demo&&e.paidDate>=from&&e.paidDate<=to&&(!category||e.category===category)).sort((a,b)=>a.paidDate.localeCompare(b.paidDate)||a.supplier.localeCompare(b.supplier,'pt-BR')||a.id.localeCompare(b.id));
}
export function groupExpenses(list){return [...new Set(list.map(e=>e.category))].map(key=>({key,name:categories[key]||'Natureza não informada',entries:list.filter(e=>e.category===key),...totals(list.filter(e=>e.category===key))})).sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'));}
export function safeCell(value){let s=String(value??'');if(/^[\s\u0000-\u001f]*[=+@-]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
export const csv=rows=>'\ufeff'+rows.map(r=>r.map(safeCell).join(';')).join('\r\n');
const source=(e,key)=>{const s=e.fieldSources?.[key];return s?.documentName?s.documentName+' · página '+(s.source?.page??'não indicada'):s?.method==='manual'?'Manual':'';};
export function detailCSV(list,documents){
 const headers=['ID','Data do pagamento','Fornecedor','CPF/CNPJ','Descrição','Natureza da despesa','Valor pago','Tratamento proposto','Pagamento conferido','Documentação conferida','Revisão fiscal','Valor dedutível revisado antes do limite','Responsável','Fundamento','Pendência','IDs dos documentos','Nomes dos documentos','Links dos documentos no Drive','Fonte do fornecedor','Fonte do CPF/CNPJ','Fonte da descrição','Fonte do valor','Fonte da data do pagamento'];
 return csv([headers,...list.map(e=>[e.id,e.paidDate,e.supplier,e.taxId,e.description,categories[e.category]||e.category,decimal(e.cents),labels[e.treatment]||e.treatment,e.paymentConfirmed?'Sim':'Não',e.docsConfirmed?'Sim':'Não',e.reviewed?'Sim':'Não',decimal(eligible(e)?e.cents:0),e.reviewer,e.reason,e.notes,e.docIds.join(' | '),e.docIds.map(id=>documents.find(d=>d.id===id)?.name||'Ausente').join(' | '),e.docIds.map(id=>documents.find(d=>d.id===id)?.driveUrl||'Ainda não sincronizado').join(' | '),...['supplier','taxId','description','amount','paidDate'].map(key=>source(e,key))])]);
}
export function summaryCSV(list,filters){return csv([['Início','Fim','Natureza da despesa','Quantidade de lançamentos','Total pago','Dedutíveis revisadas antes do limite','Não dedutíveis revisadas','Lançamentos pendentes'],...groupExpenses(list).map(g=>[filters.from,filters.to,g.name,g.entries.length,decimal(g.total),decimal(g.deduct),decimal(g.non),g.pending])]);}
export function reportHTML(list,documents,filters,{grouped=false,issuedAt=new Date()}={}){
 const t=totals(list),groups=groupExpenses(list),unlinked=documents.filter(d=>!d.demo&&d.period>=filters.from.slice(0,7)&&d.period<=filters.to.slice(0,7)&&!filters.allEntries?.some(e=>!e.demo&&e.docIds.includes(d.id)));
 const summary='<h2>Resumo por natureza</h2><table><thead><tr><th>Natureza</th><th>Qtd.</th><th>Total pago</th><th>Dedutíveis revisadas*</th><th>Não dedutíveis revisadas</th><th>Pendências</th></tr></thead><tbody>'+groups.map(g=>'<tr><td>'+esc(g.name)+'</td><td>'+g.entries.length+'</td><td>'+money(g.total)+'</td><td>'+money(g.deduct)+'</td><td>'+money(g.non)+'</td><td>'+g.pending+'</td></tr>').join('')+'</tbody></table>';
 const details=rows=>'<table><thead><tr><th>Data / natureza</th><th>Fornecedor / finalidade</th><th>Valor pago</th><th>Tratamento proposto</th><th>Conferências / pendência</th></tr></thead><tbody>'+rows.map(e=>'<tr><td>'+date(e.paidDate)+'<br>'+esc(categories[e.category]||e.category)+'</td><td>'+esc(e.supplier)+'<br>'+esc(e.description)+'</td><td>'+money(e.cents)+'</td><td>'+esc(labels[e.treatment]||e.treatment)+'</td><td>'+(pending(e)?'Pendente':'Revisado')+'<br>Pagamento: '+(e.paymentConfirmed?'conferido':'pendente')+'<br>Documentação: '+(e.docsConfirmed?'conferida':'pendente')+'<br>Revisão fiscal: '+(e.reviewed?'sim':'não')+'<br>'+esc(e.notes)+'</td></tr>').join('')+'</tbody></table>';
 return '<h1>Controle de Despesas · '+(grouped?'Relatório por natureza':'Relatório do período')+'</h1><p>Período de pagamento: '+date(filters.from)+' a '+date(filters.to)+' · Natureza: '+esc(filters.category?categories[filters.category]:'Todas')+'</p><p>Emitido em '+esc(issuedAt.toLocaleString('pt-BR'))+' · '+list.length+' lançamento(s).</p><p>Total pago: '+money(t.total)+' · Dedutíveis revisadas*: '+money(t.deduct)+' · Não dedutíveis revisadas: '+money(t.non)+' · Lançamentos pendentes: '+t.pending+'</p><p>*Antes do limite fiscal. Relatório preparatório para a contadora; a classificação proposta e as pendências continuam indicadas.</p>'+summary+(list.length?(grouped?groups.map(g=>'<h2>'+esc(g.name)+' · '+money(g.total)+'</h2>'+details(g.entries)).join(''):'<h2>Lançamentos do período</h2>'+details(list)):'<p>Nenhum lançamento salvo atende aos filtros. Documentos enviados ainda precisam ser vinculados a um lançamento.</p>')+'<h2>Fundamentos, responsáveis e comprovantes</h2>'+list.map(e=>'<div class="evidence"><p><strong>'+esc(e.supplier)+'</strong> · ID '+esc(e.id)+'<br>Fundamento: '+esc(e.reason||'Não registrado')+'<br>Responsável: '+esc(e.reviewer)+'<br>Documentos: '+e.docIds.map(id=>{const d=documents.find(d=>d.id===id);return esc(d?.name||'Ausente')+(d?.driveUrl&&/^https:\/\/drive\.google\.com\//.test(d.driveUrl)?' · <a href="'+esc(d.driveUrl)+'">Abrir no Drive</a>':'');}).join(' | ')+'</p></div>').join('')+'<h2>Documentos recebidos sem lançamento</h2><p>'+unlinked.length+' documento(s) nos meses abrangidos pelo intervalo. A natureza ainda não foi definida; esta lista não é filtrada por natureza.</p>'+unlinked.map(d=>'<p>'+esc(d.name)+' · período de recebimento '+esc(d.period)+'</p>').join('');
}
export const standaloneReport=html=>'<!doctype html><html lang="pt-BR"><meta charset="utf-8"><title>Controle de Despesas · CN2O</title><style>body{font:14px/1.5 Arial,sans-serif;color:#202a3a;max-width:1200px;margin:30px auto;padding:16px}h1,h2{color:#631325}h1{font-size:24px}h2{font-size:18px;margin-top:26px}table{border-collapse:collapse;width:100%;font-size:12px}th,td{border:1px solid #ded9d5;padding:9px;text-align:left;vertical-align:top}th{background:#faf6f2}p{margin:10px 0}.evidence{break-inside:avoid}thead{display:table-header-group}@media print{@page{size:A4 landscape;margin:14mm}body{margin:0;padding:0}}</style><body>'+html+'</body></html>';
